clean:
    # Remove todos os arquivos txt da pasta scripts/buckets
    rm -f scripts/buckets/*.txt

    # Remove todos os arquivos txt da pasta scripts/IO
    rm -f scripts/IO/*.txt

    # Remove todos os arquivos txt da pasta scripts/indexes
    rm -f scripts/indexes/*.txt